name: CI - Cloud

on:
  push:
    branches:
      - master
    paths:
      - 'functions/**'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          cd functions
          npm ci
      - name:  Deploy to Firebase
          uses: w9jds/firebase-action@master
          with:
            args: deploy --only functions
          env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

